name: CI
on:
  push:
    branches: [ develop, kendo-demo ]
  pull_request:
    branches: [ develop, kendo-demo ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v2.4.1
        with:
          node-version: "12.x"
      - name: install
        run: npm install
      - name: make public
        run: mkdir public
      - name: build
        run: npm run build:test
      - name: copy index
        run: cp public/index.html public/404.html
      - name: Deploy
        if: success()
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: public
